### PR TITLE
Switch from `faust2webaudio` to `faustwasm`

### PR DESCRIPTION
**Pull request by ijc8**

### CODE REVIEW

**Comment by ijc8** [comment]
Open question: what's depending on the assignments to `window.faust` and `window.faustEnv`?

**Comment by sletz** [comment]
@Fr0stbyteR may have an idea?

**Comment by sletz** [comment]
Thanks. After fixing the conflict I could test:
- SVG rendering is broken: the root level properly displays, but then clicking on the blue boxes should go inside the boxes hierarchy, but does not work anymore, with this error:
```
e2ae41c9-08f8-401e-be53-28351d42c742:8 Uncaught ErrnoError {node: undefined, errno: 44, code: 'ENOENT', message: 'No such file or directory', setErrno: ƒ, …}code: "ENOENT"errno: 44message: "No such file or directory"node: undefinedsetErrno: ƒ (errno)stack: "Error\n    at new ErrnoError (blob:http://127.0.0.1:8000/e2ae41c9-08f8-401e-be53-28351d42c742:8:70853)\n    at Object.open (blob:http://127.0.0.1:8000/e2ae41c9-08f8-401e-be53-28351d42c742:8:63988)\n    at Object.readFile (blob:http://127.0.0.1:8000/e2ae41c9-08f8-401e-be53-28351d42c742:8:67731)\n    at SVGAElement.<anonymous> (http://127.0.0.1:8000/dist/index.js:51984:38)\n    at HTMLDivElement.dispatch (http://127.0.0.1:8000/dist/index.js:26303:27)\n    at elemData.handle (http://127.0.0.1:8000/dist/index.js:26107:28)"[[Prototype]]: Error
    at Object.ensureErrnoError (blob:http://127.0.0.1:8000/e2ae41c9-08f8-401e-be53-28351d42c742:8:70947)
    at Object.staticInit (blob:http://127.0.0.1:8000/e2ae41c9-08f8-401e-be53-28351d42c742:8:71153)
    at blob:http://127.0.0.1:8000/e2ae41c9-08f8-401e-be53-28351d42c742:8:163145
    at instantiateFaustModuleFromFile (http://127.0.0.1:8000/dist/index.js:46917:29)
open @ e2ae41c9-08f8-401e-be53-28351d42c742:8
readFile @ e2ae41c9-08f8-401e-be53-28351d42c742:8
(anonymous) @ index.js:51984
dispatch @ index.js:26303
elemData.handle @ index.js:26107
```

**Comment by ijc8** [comment]
(Context: @sletz observed some mysterious errors when trying this PR with messages like `emsc`, `table index is out of bounds`, `memory index out of bounds`.)

@sletz Per your observations, I tried opening 10 .dsp files in Firefox and Chrome, switching between them and compiling, refreshing, checking & unchecking "Use AudioWorklet" and "Save DSP Code", enabling/disabling polyphony, etc., and none of this reproduced the issue.

However, I was finally able to reproduce by trying to compile `greyhole.dsp`. This reliably generates these errors even without any other files loaded or options checked.

This also causes issues (hanging tab) with the updated fausteditor and faustplayground, so I don't think it's an issue with faustide (or this PR) specifically.

I believe that it's instead the same issue as grame-cncm/faustwasm#3, and I suspect that it's a memory issue. Both greyhole and jpverb (used in grame-cncm/faustwasm#3) are long reverbs with big delay lines (indeed, the SuperCollider docs for [these](https://doc.sccode.org/Classes/Greyhole.html) [effects](https://doc.sccode.org/Classes/JPverb.html) include the note "Please increase server realtime memory for this to work properly"), and this explanation aligns with the error messages you've seen.

The fix will likely involve tweaking memory-related flags passed to emscripten (in https://github.com/grame-cncm/faust/blob/df02f97f7d0c4fb67fa7a7949dabcc58b199775f/build/wasmglue/CMakeLists.txt#L56) and updating faustwasm with a new build.

**Comment by sletz** [comment]
I don't think this is related to the memory consumed by the DSP code itself (that is after being compiled and instantiated), but the  Faust => wasm compilation process itself.  
I'll have a look ASAP.

**Comment by sletz** [comment]
Are conflicts difficult to solve ?

**Pull request merged**
