### PR TITLE
Add Basic Vim Mode Support to FaustIDE Monaco Editor

### PR DESCRIPTION
**Pull request by Bubobubobubobubo**
Having bindings for Vim can be much more convenient for some users and can also help them to be faster and more comfortable in the editor. This pull request is adding basic Vim bindings support. 

**Additions:**

- **Vim mode**: `vimMode` thanks to [monaco-vim](https://www.npmjs.com/package/monaco-vim). Added TypeScript types to match with the coding style and standard.
- **Vim checkbox**: added a new checkbox on the bar located at the left side of the screen.

**Caveats / Missing features:**

- **No status bar**: Vim is a modal editor and it can sometimes be useful to know in which mode the editor currently is (`INSERT`, `VISUAL`, `NORMAL`, etc). Not implementing the status bar does not seem to cause too much trouble in the context of the FaustIDE. I am opening this question for debate.
- **Crtl-R**: Vim uses Ctrl-R. This keybinding is intercepted by the Monaco Editor when the Vim mode is on.

**Note:**

This is my first contribution to this project and I hope that this is not breaking something that I am not aware of. It might interfere with some existing keybindings or shortcuts. It would be nice if an existing contributor could test the feature to tell me what is left to be done for integration 😄 .

### CODE REVIEW

**Comment by sletz** [comment]
Thanks. 
- about the existing keybindings or shortcuts, I'll let @Fr0stbyteR answer this question
- it seems that the PR dos the site generation. Usually we better want a PR **before** actual site generation. Can you report a new PR done this way ?

**Comment by Bubobubobubobubo** [comment]
> and it would be helpful to document this new feature in README.md file

Done with 8bc2506. 

> it seems that the PR does the site generation. Usually we better want a PR before actual site generation. Can you report a new PR done this way ?

Not sure about this since HTML changes are required to implement the checkbox. This commit does not include the `dist/` folder generated after the build. `package-lock.json` is a bit annoying but maybe we can let it pass through?

> about the existing keybindings or shortcuts

I'll check out how to include/exclude certain keys from monaco-vim.

**Comment by Fr0stbyteR** [comment]
I think it would be better to enable/disable the vim mode on the editor level. We can add that with the monaco-editor's own key bindings (showing if you press F1 in the editor). Could you choose one hotkey for "enable/disable the vim mode"? I'll try to implement that.

**Comment by Bubobubobubobubo** [comment]
What about `Control + Shift` + another key like `M`? `V` is probably already used for pasting.

**Comment by Fr0stbyteR** [comment]
Implemented in Bubobubobubobubo/faustide#1

**Comment by Bubobubobubobubo** [comment]
Should be good now?

**Comment by sletz** [comment]
This branch cannot be rebased due to conflicts !!

**Comment by Fr0stbyteR** [comment]
@sletz You can resolve the conflict by deleting the `package-lock.json` file and regenerate it by `npm i`.

**Comment by sletz** [comment]
I've rebased, changed the version number o this branch https://github.com/grame-cncm/faustide/tree/Bubobubobubobubo-vim. Can you @Bubobubobubobubo and @Fr0stbyteR check that it works as expected ?

**Comment by sletz** [comment]
Merged, thanks.

**Pull request closed without merging**
